import type { Metadata } from 'next'
import './globals.css'
import { ContextProvider, QueryProvider } from '../providers'


export const metadata: Metadata = {
  title: 'Wastify Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <QueryProvider>
          <ContextProvider>
            {children}
          </ContextProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
